### PR TITLE
Remove link styles so links look like links.

### PR DESCRIPTION
**Pull request by maffoo**
I like the user pages, but generally I think it's better for links to look like links. Otherwise, the user has no idea what is clickable without mousing over things.

### CODE REVIEW

**Comment by DanielSank** [comment]
Lol. I did this because with all the user names turning blue it kind of gross, which is why I had originally asked for input on the visual style. Have you looked at the pages on a dev server to see what I mean?

**Comment by maffoo** [comment]
I did look at it on the dev server, which is why I made this change. I don't mind seeing lots of links on a page (this is the web after all). What I don't particularly like is pages where you _can't_ see all the links :)

**Comment by DanielSank** [comment]
I think the underlines in links look ridiculous. Can we perhaps use our own visual style, say light blue text or something, so indicate links on this app?

**Comment by DanielSank** [comment]
Wait a second, when you run it do the link all have underlines or only when you mouse over them?

**Comment by maffoo** [comment]
I was seeing underline only when I mouse over.

**Comment by DanielSank** [comment]
Ok, sorry I don't have my dev setup on this computer and I was remembering this wrong.

Can we at least make the color a tiny bit more subdued? That bright blue just looks so jarring against the rest of the color palette. 

I'm kind of... weirded out by the fact that I'm giving you a hard time about this, but hey, this is customer facing stuff we're talking about.

**Review by DanielSank — APPROVED** [review]

**Pull request merged**
